language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install coverage flake8 mock
script:
  - export DJANGO_SETTINGS_MODULE=testtinymce.settings
  - export PYTHONPATH=$PWD:$PWD/testtinymce:$PYTHONPATH
  - flake8 tinymce --ignore=E501,E402
  - coverage run --source=tinymce setup.py test
env:
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.8"
  - DJANGO="Django==1.8.8"
  - DJANGO="Django==1.9.2"
