sudo: false
language: python
python: 2.7
addons:
  apt:
    packages:
      - libenchant-dev
env:
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - pip install coveralls
  - coveralls
