dist: bionic
sudo: false
language: python
cache: pip
install: pip install tox tox-travis
script: tox -v
python:
  - 3.6
  - 3.7
  - 3.8
matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: TOX_ENV=flake8
addons:
  apt:
    packages:
      - libenchant-dev
after_success:
  - pip install coveralls
  - coveralls
