dist: bionic
sudo: false
language: python
cache: pip
install: pip install tox tox-travis
script: tox -v
python:
  - 3.6
  - 3.7
  - 3.8
jobs:
  fast_finish: true
  include:
    - name: "Code checks"
      python: 3.8
      install: pip install pre-commit
      script:
        pre-commit run --all-files --show-diff-on-failure

addons:
  apt:
    packages:
      - libenchant-dev
after_success:
  - pip install coveralls
  - coveralls
