dist: bionic
sudo: false
language: python
cache: pip
install: pip install tox tox-travis
script: tox -v
python:
  - 3.6
  - 3.7
  - 3.8
jobs:
  fast_finish: true
  include:
    - name: "Code checks"
      python: 3.8
      install: pip install pre-commit
      script:
        pre-commit run --all-files --show-diff-on-failure
    - stage: deploy
      env:
      python: 3.7
      script: skip
      deploy:
        provider: pypi
        user: jazzband
        server: https://jazzband.co/projects/django-tinymce/upload
        distributions: sdist bdist_wheel
        password:
          secure: ayxnrMEzO84D3sOmA2KSMWhixBukz1VxvtwoERHrPz+drhR+Cgj+c/KsUvoPjWlASzUTCbOVW43CyxYbcamDN6B362ZwFEy3XtIlPb1XxyE2lAcnjY1NPtx7CRw0lRfQTFACb4m5TgAu0St/TiakNaelTTYrB18qye9W4cwHVyw=
        skip_existing: true
        on:
          tags: true
          repo: jazzband/django-tinymce
          python: 3.7
addons:
  apt:
    packages:
      - libenchant-dev
after_success:
  - pip install coveralls
  - coveralls
